<?php
/*
|--------------------------------------------------------------------------
| Documentation
|--------------------------------------------------------------------------
|
| These settings are used to properly generate documentation using Sereno.
| If docs directory is present in the `content` directory, then the
| docs are generated automatically.
|
*/
return [
    /*
    |--------------------------------------------------------------------------
    | Directory
    |--------------------------------------------------------------------------
    |
    | Here you may specify which directory (relative to content) to use
    | for generating your docs.
    |
    */
    'directory'  => 'docs',

    /*
    |--------------------------------------------------------------------------
    | URL prefix
    |--------------------------------------------------------------------------
    |
    | Pages generated by docs builder are prefixed with this value.
    |
    */
    'url_prefix' => 'docs',

    /*
    |--------------------------------------------------------------------------
    | Index
    |--------------------------------------------------------------------------
    |
    | This file is used to generate sidebar for docs page.
    |
    */
    'index' => 'documentation',

    /*
    |--------------------------------------------------------------------------
    | Markdown Configuration for Documentation
    |--------------------------------------------------------------------------
    |
    | Docs pages have a different style (inspired & stolen from Laravel).
    |
    */
    'extends' => 'docs.base',
    'yields'  => 'doc_content',

    /*
    |--------------------------------------------------------------------------
    | Docs Landing Page
    |--------------------------------------------------------------------------
    |
    | Here you may specify which file to load by default if user visits
    | docs landing page.
    |
    */
    'default' => 'installation',

    /*
    |--------------------------------------------------------------------------
    | Redirection
    |--------------------------------------------------------------------------
    |
    | Whether or not the documentation should make a copy of the default page
    | or if it should redirect to that page.
    |
    */
    'redirect' => false,
];
